name: Publish on Docker Hub

on:
  release:
    types: [published]

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set TAG
        run: |
          echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          echo "TAG=${{ github.event.release.tag_name }}"
          
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build image, retag and push
        if: success()
        run: |
          docker build -t ethersphere/latitudesh-bee-blueprint:${TAG} .
          docker tag ethersphere/latitudesh-bee-blueprint:${TAG} ethersphere/latitudesh-bee-blueprint:latest
          docker push ethersphere/latitudesh-bee-blueprint:${TAG}
          docker push ethersphere/latitudesh-bee-blueprint:latest